Payroll/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\jabatan\JabatanController;
use App\Http\Controllers\karyawan\karyawanController;
use App\Http\Controllers\transaksi\TransaksiController;
use App\Http\Controllers\gaji\GajiController;
use App\Http\Controllers\user\UserController;
use App\Http\Controllers\auth\AuthController;
use App\Http\Controllers\dashboard\DashboardController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/login', function () {
    return view('dashboard.login.login');
});
Route::get('utama', [DashboardController::class, 'dashboard'])->name('dasboard');

Route::post('login', [AuthController::class, 'login'])->name('login.action');
Route::get('logout', [AuthController::class, 'logout'])->name('logout');

Route::Resource('/gaji', GajiController::class);
Route::Resource('/master/jabatan', JabatanController::class);
Route::Resource('/master/karyawan', karyawanController::class);
Route::Resource('/transaksi', TransaksiController::class);

Route::put('/account-active/{id}', [UserController::class, 'activate'])->name('account-active.activate');
Route::put('/account-ban/{id}', [UserController::class, 'ban'])->name('account-ban.ban');
Route::Resource('/account', UserController::class);

Route::get('/kabupaten', [karyawanController::class, 'kabupaten'])->name('kabupaten.kabupaten');
Route::get('/kecamatan', [karyawanController::class, 'kecamatan'])->name('kecamatan.kecamatan');

Payroll/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    protected $table = 'users';
    protected $primaryKey = 'id';
    protected $fillable = [
        'id_karyawan',
        'name',
        'email',
        'password',
        'id_role',
        'isActive'
    ];

    protected $hidden = [
        'password',
        'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

Payroll/app/Http/Controllers/user/UserController.php
<?php

namespace App\Http\Controllers\user;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\User\UserStore;
use App\Http\Requests\User\UserUpdate;
use App\Models\User;
use App\Models\karyawan\Karyawan;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\View;
use Illuminate\Support\Facades\Hash;
class UserController extends Controller
{
    const FETCHED_ATTRIBUTE = [
        'id_role',
        'id_karyawan',
        'name',
        'email',
        'password',
        'isActive'
    ];
    public function index(Request $request)
    {
        $account = User::orderBy('created_at', 'desc')
            ->get();
        return view('dashboard.content.user.user', compact('account'));
    }

    public function create()
    {
        $karyawan = Karyawan::get();
        $action = 'add';
        return view('dashboard.content.user.user-action', compact('action','karyawan'));
    }

    public function store(UserStore $request)
    {
        $data = $request->only(self::FETCHED_ATTRIBUTE);
        $data['id_role'] = 1;
        $data['isActive'] = 1;
        $data['password']=Hash::make($data['password']);
        $karyawan = Karyawan::findOrFail($data['id_karyawan']);
        $data['name']=$karyawan->nama;
        $account = User::create($data);
        
        return redirect('account')->with('success', 'Account berhasil ditambah !');
    }

    public function edit($id)
    {
        $karyawan = Karyawan::get();
        $action = 'edit';
        $account = User::findOrFail($id);
        return view('dashboard.content.user.user-action', compact('action', 'account','karyawan'));
    }

    public function update(UserUpdate $request,User $account)
    {
        $data = $request->only(self::FETCHED_ATTRIBUTE);
        $data['password']=Hash::make($data['password']);
        $karyawan = Karyawan::findOrFail($data['id_karyawan']);
        $data['name']=$karyawan->nama;
        $account->update($data);

        return redirect('account')->with('success', 'Account berhasil diedit !');
    }

    public function destroy(User $user)
    {
        
        $user->delete();
        return redirect('account')->with('success', 'Account berhasil dihapus !');
    }


    public function activate($id, Request $request)
    {
        $user = User::findOrFail($id);
        $data = $request->all();
        $user->update([
            'isActive' => 1
        ]);


        return redirect('/account')->with('success', 'Account berhasil diaktifkan !');
    }

    public function ban($id, Request $request)
    {
        $user = User::findOrFail($id);
        $data = $request->all();
        $user->update([
            'isActive' => 0
        ]);

        return redirect('/account')->with('success', 'Account berhasil diban !');
    }
}

Payroll/resources/views/dashboard/content/user/user-action.blade.php
@extends('dashboard.dashboard')

@section('content')
<div class="container-fluid p-0">
  <div class="row d-flex justify-content-center">
    <div class="col-8">
      @if($action == 'add')
        <h1 class="h3 mb-3">Add New User</h1>
      @else
        <h1 class="h3 mb-3">Edit User</h1>
      @endif
      <div class="card">
        <div class="card-header">
          <h5 class="card-title mb-0">
            @if($action == 'add')
              <form id="account-action" action="{{ route('account.store') }}" method="POST" enctype="multipart/form-data">
            @else
              <form id="account-action" action="{{ route('account.update', $account->id) }}" method="post" enctype="multipart/form-data">
              @method('put')
            @endif
            @csrf
            <div class="mb-3">
              <label for="fullname" class="form-label">Karyawan</label><span class="text-danger">*</span>
              <select class="form-select @error('id_karyawan') is-invalid @enderror" name="id_karyawan" aria-label="Default select example" id="id_karyawan">
                <option selected disabled value="">Karyawan Anda</option>
                  @foreach ($karyawan as $item)
                    <option value="{{$item['id']}}">{{$item['nama']}}</option>
                  @endforeach
                @if ($action=="edit")
                  @foreach ($karyawan as $item)
                    <option value="{{$item['id']}}" <?php if($account->id_karyawan == $item['id']) { echo "selected";} ?>>{{$item['nama']}}</option>
                  @endforeach
                @endif
                @if(old('id_karyawan'))
                    @foreach($karyawan as $item)
                    <option value="{{$item['id']}}" {{ ($item['id'] == old('id_karyawan')) ? 'selected="selected"' : '' }}>{{$item['nama']}}</option>
                    @endforeach
                @endif
              </select>
              @error('id_karyawan')
                  <div class="invalid-feedback">{{ $message }}</div>
              @enderror
              </div>
              <div class="mb-3">
                <label class="form-label">E-mail</label><span class="text-danger">*</span>
                <input type="text" class="form-control @error('email') is-invalid @enderror" name="email" id="email" value="{{ old('email') }}">
                @error('email')
                    <div class="invalid-feedback">{{ $message }}</div>
                @enderror
              </div>
              <div class="mb-3">
                <label class="form-label">Password</label><span class="text-danger">*</span>
                <input type="password" class="form-control @error('password') is-invalid @enderror" name="password" id="password" value="{{ old('password') }}">
                @error('password')
                    <div class="invalid-feedback">{{ $message }}</div>
                @enderror
              </div>
              <div class="d-flex justify-content-center">
                <a href="{{route('account.index')}}" class="btn btn-light me-2">
                    <span class="btn-icon-label">
                      <i data-feather="arrow-left" class="me-2"></i>
                        <span> Kembali </span>
                    </span>
                </a>
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>
          </h5>
        </div>
        <div class="card-body">
        </div>
      </div>
    </div>
  </div>

</div>
@endsection

@section('page-script')
<script>
  @if($action=='edit')
    const account = {!! json_encode($account->toArray()) !!}
    email.value = account.email
  @endif

</script>
@endsection

Payroll/resources/views/dashboard/content/user/user.blade.php
@extends('dashboard.dashboard')

@section('content')
<div class="container-fluid p-0">

  <h1 class="h3 mb-3">Account</h1>

  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header pt-4">
          <div class="d-flex justify-content-between align-items-center">
            <h5 class="card-title mb-0">List User</h5>
            <a href="{{route('account.create')}}" role="button" class="btn btn-primary">
              Add User
            </a>
          </div>

        </div>
        <div class="card-body">
          <table id="MyTable" class="table table-bordered" style="width:100%">
            <thead class="table-primary">
              <tr class="text-center">
                <th>No. </th>
                <th>User</th>
                <th>Email</th>
                <th>Status</th>
                <th>Action</th>

              </tr>
            </thead>
            <tbody>
              @foreach ($account as $key=>$accounts)
              <tr>
                <td class="text-center">{{$loop->iteration}}</td>
                <td>
                  {{$accounts->name}}
                </td>
                <td>{{$accounts->email}}</td>
                <td>
                  @if($accounts->isActive==1)
                  <span class="badge bg-success">Active
                  </span>
                  @elseif($accounts->isActive==0)
                  <span class="badge bg-danger">Ban</span>
                  @endif
                </td>

                <td>
                  <div class="dropstart d-flex justify-content-center">
                    <button class="btn" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                      <i class="fas fa-ellipsis-v"></i>
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                      <li><a class="dropdown-item" href="{{ route('account.edit', $accounts->id) }}">Edit</a></li>
                      <li><a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#delete-modal" data-bs-id="{{$accounts->id}}" data-bs-act="{{ route('account.destroy', $accounts->id) }}" data-bs-title="{{$accounts->name}}">Delete</a></li>
                      @if($accounts->isActive==1)
                      <li><a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#ban" data-bs-id="{{$accounts->id}}" data-bs-act="{{ route('account-ban.ban', $accounts->id) }}" data-bs-name="{{$accounts->name}}">Ban</a></li>
                      @elseif($accounts->isActive==0)
                      <li><a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#active" data-bs-id="{{$accounts->id}}" data-bs-act="{{ route('account-active.activate', $accounts->id) }}" data-bs-name="{{$accounts->name}}">UnBan</a></li>
                      @endif
                    </ul>
                  </div>
                </td>
              </tr>
              @endforeach
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Modal active -->
<div class="modal fade" id="active" tabindex="-1" aria-labelledby="activeModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="activeModalLabel">Activate Account</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <form id="active-form" action="/" method="post">
        <div class="modal-body">
          Are you sure you want to active user <strong id="active-name"></strong>
        </div>
        @csrf
        @method('PUT')
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-success">Active</button>
        </div>
      </form>
    </div>
  </div>
</div>

<!-- Modal ban -->
<div class="modal fade" id="ban" tabindex="-1" aria-labelledby="banModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="banModalLabel">Ban Account</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <form id="ban-form" action="/" method="post">
        <div class="modal-body">
          Are you sure you want to ban user <strong id="ban-name"></strong>
        </div>
        @csrf
        @method('PUT')
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-danger">ban</button>
        </div>
      </form>
    </div>
  </div>
</div>
<!-- Modal delete -->
<div class="modal modal-confirmation fade" id="delete-modal" tabindex='-1' role="dialog" aria-labelledby="deleteData" aria-hidden="true">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <form id="delete-form" action="/" method="post">
        <div class="modal-body">
          <h4>Konfirmasi</h4>
          <p class="mb-0">Yakin untuk menghapus <strong id="del-name"> </strong></p>
        </div>
        <div class="modal-footer">
          @csrf
          @method('DELETE')
          <button type="button" class="btn btn-link" data-bs-dismiss="modal">Batal</button>
          <button type="submit" class="btn btn-danger">Hapus</button>
        </div>
      </form>
    </div>
  </div>
</div>
@endsection

@section('page-script')
<script>
  document.addEventListener("DOMContentLoaded", x => {

    const activeModal = document.getElementById('active');
    const activeForm = document.getElementById('active-form');

    const banModal = document.getElementById('ban');
    const banForm = document.getElementById('ban-form');

    const deleteModal = document.getElementById('delete-modal');
    const deleteForm = document.getElementById('delete-form');

    // active Modal Script
    activeModal.addEventListener('show.bs.modal', evt => {
      let activeBtn = event.relatedTarget;
      activeForm.action = activeBtn.getAttribute('data-bs-act');
      activeModal.querySelector('#active-name').textContent = '"' + activeBtn.getAttribute('data-bs-name') + '" ?'
    })

    // ban Modal Script
    banModal.addEventListener('show.bs.modal', evt => {
      let banBtn = event.relatedTarget;
      banForm.action = banBtn.getAttribute('data-bs-act');
      banModal.querySelector('#ban-name').textContent = '"' + banBtn.getAttribute('data-bs-name') + '" ?'
    })

    // Delete Modal Script
    deleteModal.addEventListener('show.bs.modal', evt => {
      let deleteBtn = event.relatedTarget;
      deleteForm.action = deleteBtn.getAttribute('data-bs-act');
      deleteModal.querySelector('#del-name').textContent = '"' + deleteBtn.getAttribute('data-bs-title') + '" ?'
    })

  });
</script>
@endsection