Payroll/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\jabatan\JabatanController;
use App\Http\Controllers\karyawan\karyawanController;
use App\Http\Controllers\transaksi\TransaksiController;
use App\Http\Controllers\gaji\GajiController;
use App\Http\Controllers\user\UserController;
use App\Http\Controllers\auth\AuthController;
use App\Http\Controllers\dashboard\DashboardController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/login', function () {
    return view('dashboard.login.login');
});
Route::get('utama', [DashboardController::class, 'dashboard'])->name('dasboard');

Route::post('login', [AuthController::class, 'login'])->name('login.action');
Route::get('logout', [AuthController::class, 'logout'])->name('logout');

Route::Resource('/gaji', GajiController::class);
Route::Resource('/master/jabatan', JabatanController::class);
Route::Resource('/master/karyawan', karyawanController::class);
Route::Resource('/transaksi', TransaksiController::class);

Route::put('/account-active/{id}', [UserController::class, 'activate'])->name('account-active.activate');
Route::put('/account-ban/{id}', [UserController::class, 'ban'])->name('account-ban.ban');
Route::Resource('/account', UserController::class);

Route::get('/kabupaten', [karyawanController::class, 'kabupaten'])->name('kabupaten.kabupaten');
Route::get('/kecamatan', [karyawanController::class, 'kecamatan'])->name('kecamatan.kecamatan');

Payroll/app/Models/transaksi/Transaksi.php
<?php

namespace App\Models\transaksi;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\detail\Detail;
class Transaksi extends Model
{
    use HasFactory;
    protected $primaryKey='id';
    protected $table='transaksis';
    protected $fillable=['kode','nominal'];
    public function detail()
    {
        return $this->hasMany(Detail::class, "id_transaksi", "id");
    }
}

Payroll/app/Http/Controllers/transaksi/TransaksiController.php
<?php

namespace App\Http\Controllers\transaksi;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\transaksi\Transaksi;
use App\Models\karyawan\Karyawan;
use App\Models\detail\Detail;
use App\Models\gaji\Gaji;
use App\Http\Requests\transaksi\TransaksiStore;
use App\Http\Requests\transaksi\TransaksiUpdate;
class TransaksiController extends Controller
{
    Const FETCHED_ATTRIBUTE = [
        'id_karyawan',
        'id_transaksi',
        'nominal',
        'kode',
        'jumlah',
        'persen',
        'total'
    ];
    public function index()
    {
        $transaksi = Transaksi::with(['detail.karyawan'])->orderBy('created_at', 'desc')
        ->get();
        return view('dashboard.content.transaksi.transaksi', compact('transaksi'));
    }

    public function create()
    {
        $karyawan = Karyawan::get();
        $action = 'add';
        return view('dashboard.content.transaksi.transaksi-action', compact('action','karyawan'));
    }

    public function store(TransaksiStore $request)
    {
        $data = $request->only(self::FETCHED_ATTRIBUTE);
        $karyawan=$request->id_karyawan;
        $persen=$request->persen;
        $persenJumlah=array_sum($persen);

        if($persenJumlah!=100){
            return redirect('/transaksi')->with(['error' => 'Data Tidak 100%!']);
        }else{
            $transaksi = Transaksi::create($data);
            for ($i=0; $i < count($karyawan); $i++) {
                    $gaji= Gaji::where('id_karyawan',$karyawan[$i])->first();
                    $jumlah=$data['nominal'] * $persen[$i] / 100;

                    $total=null;
                    if($gaji){
                        $total=$gaji['tunjangan']+$gaji['gaji_pokok']+$jumlah;
                    }else{
                        $total=0;
                    }
                    
                    $save=array(
                        "id_karyawan"=>$karyawan[$i],
                        "id_transaksi"=>$transaksi->id,
                        "jumlah"=>$jumlah,
                        "persen"=>$persen[$i],
                        "total"=>$total
                    );
                    $detail=Detail::create($save);
            
                
            }
            return redirect('/transaksi')->with(['success' => 'Data Berhasil Ditambahkan!']);
        }
        
    }
    public function show($id)
    {
         $transaksi = Transaksi::where('id', $id)->with('detail.karyawan')->first();
         return view('dashboard.content.transaksi.transaksi-show', compact('transaksi'));
    }

    public function edit($id)
    {
        $action = 'edit';
        $karyawan = Karyawan::get();
        $transaksi = Transaksi::findOrFail($id)->load('detail.transaksi');
        return view('dashboard.content.transaksi.transaksi-action', compact('action','transaksi','karyawan'));
    }

    public function update(TransaksiUpdate $request, Transaksi $transaksi)
    {
        $data = $request->only(self::FETCHED_ATTRIBUTE);
        
        $karyawan=$request->id_karyawan;
        $persen=$request->persen;
        $persenJumlah=array_sum($persen);

        if($persenJumlah!=100){
            return redirect('/transaksi')->with(['error' => 'Data Tidak 100%!']);
        }else{
            $transaksi->update($data);
            Detail::where('id_transaksi',$transaksi->id)->delete();
            for ($i=0; $i < count($karyawan); $i++) {
                    $jumlah=$data['nominal'] * $persen[$i] / 100;
                    $save=array(
                        "id_karyawan"=>$karyawan[$i],
                        "id_transaksi"=>$transaksi->id,
                        "jumlah"=>$jumlah,
                        "persen"=>$persen[$i],
                        "total"=>$jumlah
                    );
                    
                    $detail=Detail::create($save);

            }
            return redirect('/transaksi')->with(['success' => 'Data Berhasil Diupdate!']);
        }
        
    }

    public function destroy(Transaksi $transaksi)
    {
        $detail=Detail::where('id_transaksi',$transaksi)->delete();
        $transaksi->delete();
        return redirect('/transaksi')->with(['success' => 'Data Berhasil DiHapus!']);
    }
}

Payroll/resources/views/dashboard/content/transaksi/transaksi-action.blade.php
@extends('dashboard.dashboard')

@section('content')
<div class="container-fluid p-0">
  <div class="row d-flex justify-content-center">
    <div class="col-8">
        @if($action == 'add')
            <h1 class="h3 mb-3">Add New Transaksi</h1>
        @else
            <h1 class="h3 mb-3">Edit Transaksi</h1>
        @endif
      <div class="card">
        <div class="card-header">
          <h5 class="card-title mb-0">
            @if($action == 'add')
                <form id="transaksi-action" action="{{ route('transaksi.store') }}" method="POST" enctype="multipart/form-data">
            @else
                <form id="transaksi-action" action="{{ route('transaksi.update', $transaksi->id) }}" method="post" enctype="multipart/form-data">
                @method('put')
            @endif
                @csrf
                <div class="mb-3">
                    <label for="fullname" class="form-label">Kode</label><span class="text-danger">*</span>
                    <input type="text" name="kode" class="form-control @error('kode') is-invalid @enderror" value="{{ old('kode') }}" id="kode" placeholder="kode anda">
                    @error('kode')
                        <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>
                <div class="mb-3">
                    <label for="fullname" class="form-label">nominal</label><span class="text-danger">*</span>
                    <input type="number" name="nominal" class="form-control @error('nominal') is-invalid @enderror" value="{{ old('nominal') }}" id="nominal" placeholder="nominal anda">
                    @error('nominal')
                        <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>
                <div class="mb-3">
                  <div class="row targetDiv" id="div0">
                    <div class="col-md-12">
                      <div id="group1" class="fvrduplicate">
                        @if ($action=='edit')
                          @foreach ($transaksi->detail as $value)
                            <div class="row entry">
                              <div class="col-xs-12 col-md-5">
                                <div class="form-group">
                                  <label>Karyawan</label>
                                  <select class="form-select @error('id_karyawan') is-invalid @enderror" name="id_karyawan[]" aria-label="Default select example" id="id_karyawan[]">
                                    <option selected disabled value="">Karyawan Anda</option>
                                    @foreach ($karyawan as $item)
                                        <option value="{{$item['id']}}" <?php if($value->id_karyawan == $item['id']) { echo "selected";} ?>>{{$item['nama']}}</option>
                                    @endforeach
                                    @if(old('id_karyawan'))
                                        @foreach($karyawan as $item)
                                        <option value="{{$item['id']}}" {{ ($item['id'] == old('id_karyawan')) ? 'selected="selected"' : '' }}>{{$item['nama']}}</option>
                                        @endforeach
                                    @endif
                                  </select>
                                  @error('id_karyawan')
                                      <div class="invalid-feedback">{{ $message }}</div>
                                  @enderror
                                </div>
                              </div>
                              <div class="col-xs-12 col-md-5">
                                <div class="form-group">
                                  <label>Persen</label>
                                  <input class="form-control form-control-sm" name="persen[]" type="number" value="{{$value->persen}}" placeholder="10">
                                </div>
                              </div>
                              <div class="col-xs-12 col-md-2">
                                <div class="form-group">
                                  <label>&nbsp;</label>
                                  <button type="button" class="btn btn-success btn-sm btn-add">
                                    <i class="fa fa-plus" aria-hidden="true"></i>
                                  </button>
                                </div>
                              </div>
                            </div>
                          @endforeach
                        @endif
                        <div class="row entry">
                          <div class="col-xs-12 col-md-5">
                            <div class="form-group">
                              <label>Karyawan</label>
                              <select class="form-select @error('id_karyawan') is-invalid @enderror" name="id_karyawan[]" aria-label="Default select example" id="id_karyawan[]">
                                <option selected disabled value="">Karyawan Anda</option>
                                @foreach ($karyawan as $item)
                                    <option value="{{$item['id']}}">{{$item['nama']}}</option>
                                @endforeach
                                @if(old('id_karyawan'))
                                    @foreach($karyawan as $item)
                                    <option value="{{$item['id']}}" {{ ($item['id'] == old('id_karyawan')) ? 'selected="selected"' : '' }}>{{$item['nama']}}</option>
                                    @endforeach
                                @endif
                              </select>
                              @error('id_jabatan')
                                  <div class="invalid-feedback">{{ $message }}</div>
                              @enderror
                            </div>
                          </div>
                          <div class="col-xs-12 col-md-5">
                            <div class="form-group">
                              <label>Persen</label>
                              <input class="form-control form-control-sm" name="persen[]" type="number" placeholder="10">
                            </div>
                          </div>
                          <div class="col-xs-12 col-md-2">
                            <div class="form-group">
                              <label>&nbsp;</label>
                              <button type="button" class="btn btn-success btn-sm btn-add">
                                <i class="fa fa-plus" aria-hidden="true"></i>
                              </button>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              
              

              <div class="d-flex justify-content-center">
                <a href="{{route('transaksi.index')}}" class="btn btn-light me-2">
                    <span class="btn-icon-label">
                      <i data-feather="arrow-left" class="me-2"></i>
                        <span> Kembali </span>
                    </span>
                </a>
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>
          </h5>
        </div>
        <div class="card-body">
        </div>
      </div>
    </div>
  </div>

</div>
@endsection

@section('page-script')
<script>

@if($action=='edit')
  const transaksi = {!! json_encode($transaksi->toArray()) !!}

    kode.value = transaksi.kode
    nominal.value = transaksi.nominal

@endif

                
$(function() {
    $(document).on('click', '.btn-add', function(e) {
        e.preventDefault();
        var controlForm = $(this).closest('.fvrduplicate'),
            currentEntry = $(this).parents('.entry:first'),
            newEntry = $(currentEntry.clone()).appendTo(controlForm);
        newEntry.find('input').val('');
        controlForm.find('.entry:not(:last) .btn-add')
            .removeClass('btn-add').addClass('btn-remove')
            .removeClass('btn-success').addClass('btn-danger')
            .html('<i class="fa fa-minus" aria-hidden="true"></i>');
    }).on('click', '.btn-remove', function(e) {
        $(this).closest('.entry').remove();
        return false;
    });
});
</script>
@endsection

Payroll/resources/views/dashboard/content/transaksi/transaksi-show.blade.php
@extends('dashboard.dashboard')

<head>
  <style>
    :root {
      --white: #ffffff;
     
      --black-darker: #2c2c2c;
      --blue: #005099;
      --gray: #f3f3f3;
      --gray-darker: #d0d0d0;
      --gray-more-darker: #8a8a8e;
      --border-radius: 6px;
      --body-font-size: 18px;
      --small-font-size: 14px;
      --smaller-font-size: 12px;
    }

    #cta {
      margin-bottom: 43px;
    }

    .card-member {
      border-radius: calc(var(--border-radius) * 2);
      border: 1px solid var(--gray-darker);
      background-color: var(--white);
      overflow: hidden;
      padding: 240px 40px 40px 40px;
      position: relative;
    }

    .card-member .card-member-bg {
      position: absolute;
      width: 100%;
      top: 0;
      left: 0;
      right: 0;
      height: 300px;
      object-fit: contain;
    }

    .card-member .card-member-avatar {
      display: block;
      margin: 0 auto;
      width: 120px;
      height: 120px;
      position: relative;
      z-index: 2;
      margin-bottom: 32px;
      border-radius: 50%;
      object-fit: cover;
      background-color: white;
    }

    .card-member .card-member-name {
      font-size: 28px;
      font-weight: 700;
      color: var(--blue);
      margin-bottom: 12px;
      text-align: center;
    } .card-member .card-member-ceo {
      font-size: 18px;
      font-weight: 600;
      color: var(--black-darker);
      margin-bottom: 12px;
      text-align: center;
    }

    .card-member .card-member-id {
      margin-bottom: 56px;
      text-align: center;
    }

    .card-member-info-wrapper {
      max-width: 100%;
      width: 528px;
      margin-left: auto;
      margin-right: auto;
      margin-bottom: 35px;
    }

    .card-member-info {
      padding: 16px;
      border-radius: calc(var(--border-radius) * 2);
      background-color: var(--gray);
      text-align: center;
    }

    .card-member-info .card-member-info-title {
      margin-bottom: 12px;
    }

    .card-member-info .card-member-info-amount {
      margin-bottom: 0;
      font-size: 28px;
      font-weight: 700;
      color: var(--blue);
    }

    .card-member .card-member-desc {
      margin-bottom: 33px;
    }

    .table-detail {
      margin-bottom: 32px;
    }

    table tr td:last-child {
      display: flex;
      align-items: flex-start;
    }

    .cap {
    text-transform: capitalize;
    }
  </style>
</head>
@section('content')
<div class="container-fluid p-0">
  <div class="row d-flex justify-content-center">
    <div class="col-8">
      <h1 class="h3 mb-3">Show</h1>
      <div class="card">
        <div class="card-body">
          <div class="accordion" id="accordionPanelsStayOpenExample">
            <div class="accordion-item">
              <h2 class="accordion-header" id="panelsStayOpen-headingOne">
                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true" aria-controls="panelsStayOpen-collapseOne">
                  Transaksi
                </button>
              </h2>
              <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse show" aria-labelledby="panelsStayOpen-headingOne">
                <div class="accordion-body">
                    <div class="row">
                      <div class="col-3 text-end text-secondary">Kode</div>
                      <div class="col-9">{{$transaksi->kode}}</div>

                    <div class="col-3 text-end text-secondary">Nominal</div>
                    <div class="col-9">{{$transaksi->nominal}}</div>
                    
                  </div>
                </div>
              </div>
            </div>
            <div class="accordion-item">
              <h2 class="accordion-header" id="panelsStayOpen-headingTwo">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">
                  Pembagian
                </button>
              </h2>
              <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingTwo">
                <div class="accordion-body">
                  <div class="row">
                      @foreach ($transaksi->detail as $key=>$item)
                        <div class="col-3 text-end text-secondary">Karyawan {{$key+1}}</div>
                        <div class="col-9">{{$item->karyawan->nama}}</div>
                        <div class="col-3 text-end text-secondary">Persentase</div>
                        <div class="col-9">{{$item->persen}} %</div>
                        <div class="col-3 text-end text-secondary">Jumlah</div>
                        <div class="col-9">Rp.{{number_format($item->jumlah, 0, ".", ".")}}</div>
                        <div class="col-3 text-end text-secondary">Total</div>
                        <div class="col-9">Rp.{{number_format($item->total, 0, ".", ".")}}</div>
                        <br>
                      @endforeach
                    
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="d-flex justify-content-center mt-3">
            <a href="{{route('transaksi.index')}}" class="btn btn-light me-2">
                <span class="btn-icon-label">
                  <i data-feather="arrow-left" class="me-2"></i>
                    <span> Kembali </span>
                </span>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>
@endsection

@section('page-script')
@endsection

Payroll/resources/views/dashboard/content/transaksi/transaksi.blade.php
@extends('dashboard.dashboard')

@section('content')
<div class="container-fluid p-0">

  <h1 class="h3 mb-3">Transaksi</h1>

  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header pt-4">
          <div class="d-flex justify-content-between align-items-center">
            <h5 class="card-title mb-0">Transaksi</h5>
            <a href="{{route('transaksi.create')}}" type="button" class="btn btn-primary">
              Add Transaksi</a>
          </div>

        </div>
        <div class="card-body">
          <table id="MyTable" class="table table-bordered" style="width:100%">
            <thead class="table-primary">
              <tr class="text-center">
                <th>
                  No.
                </th>
                <th>Kode</th>
                <th>Nominal</th>
                <th>Action</th>

              </tr>
            </thead>
            <tbody>
              @forelse($transaksi as $item)
              <tr>
                <td class="text-center">{{$loop->iteration}}</td>
                <td>{{$item->kode}}</td>
                <td>{{$item->nominal}}</td>
                <td width="10" class="text-center">
                  <div class="dropstart d-flex justify-content-center">
                      <button class="btn" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                          <i class="fas fa-ellipsis-v"></i>
                      </button>
                      <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                        <li><a class="dropdown-item" href="{{ route('transaksi.show', $item->id) }}">Show</a></li>
                          <li><a class="dropdown-item" href="{{ route('transaksi.edit', $item->id) }}">Edit</a></li>
                          <li><a class="dropdown-item" href="#" data-bs-toggle="modal" data-bs-target="#delete-modal" data-bs-id="{{$item->id}}" data-bs-act="{{ route('transaksi.destroy', $item->id) }}" data-bs-kode="{{$item->kode}}">Delete</a></li>
                      </ul>
                  </div>
                </td>
              </tr>
              @empty
              <tr>
                <td colspan="8">
                  <center>Data kosong</center>
                </td>
              </tr>
              @endforelse
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal modal-confirmation fade" id="delete-modal" tabindex='-1' role="dialog" aria-labelledby="deleteData" aria-hidden="true">
  <div class="modal-dialog modal-sm" role="document">
      <div class="modal-content">
          <form id="delete-form" action="/" method="post" enctype="multipart/form-data">
              @csrf
              <div class="modal-body">
                  <h4>Konfirmasi</h4>
                  <p class="mb-0">Yakin untuk menghapus <strong id="del-name"> </strong></p>
              </div>
              <div class="modal-footer">
                  @method('DELETE')
                  <button type="button" class="btn btn-link" data-bs-dismiss="modal">Batal</button>
                  <button type="submit" class="btn btn-danger">Hapus</button>
              </div>
          </form>
      </div>
  </div>
</div>

@endsection
<script>
  document.addEventListener("DOMContentLoaded", x => {

      const deleteModal = document.getElementById('delete-modal');
      const deleteForm = document.getElementById('delete-form');

      // Delete Modal Script
      deleteModal.addEventListener('show.bs.modal', evt => {
          let deleteBtn = event.relatedTarget;
          deleteForm.action = deleteBtn.getAttribute('data-bs-act');
          deleteModal.querySelector('#del-name').textContent = '"' + deleteBtn.getAttribute('data-bs-kode') + '" ?'
      })

  });
</script>