Payroll/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\jabatan\JabatanController;
use App\Http\Controllers\karyawan\karyawanController;
use App\Http\Controllers\transaksi\TransaksiController;
use App\Http\Controllers\gaji\GajiController;
use App\Http\Controllers\user\UserController;
use App\Http\Controllers\auth\AuthController;
use App\Http\Controllers\dashboard\DashboardController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/login', function () {
    return view('dashboard.login.login');
});
Route::get('utama', [DashboardController::class, 'dashboard'])->name('dasboard');

Route::post('login', [AuthController::class, 'login'])->name('login.action');
Route::get('logout', [AuthController::class, 'logout'])->name('logout');

Route::Resource('/gaji', GajiController::class);
Route::Resource('/master/jabatan', JabatanController::class);
Route::Resource('/master/karyawan', karyawanController::class);
Route::Resource('/transaksi', TransaksiController::class);

Route::put('/account-active/{id}', [UserController::class, 'activate'])->name('account-active.activate');
Route::put('/account-ban/{id}', [UserController::class, 'ban'])->name('account-ban.ban');
Route::Resource('/account', UserController::class);

Route::get('/kabupaten', [karyawanController::class, 'kabupaten'])->name('kabupaten.kabupaten');
Route::get('/kecamatan', [karyawanController::class, 'kecamatan'])->name('kecamatan.kecamatan');

Payroll/app/Models/karyawan/Karyawan.php
<?php

namespace App\Models\Karyawan;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\jabatan\Jabatan;
use App\Models\gaji\Gaji;
use App\Models\detail\Detail;
class Karyawan extends Model
{
    use HasFactory;
    protected $primaryKey='id';
    protected $table='karyawans';
    protected $fillable=['nama','email','id_jabatan','alamat','kabupaten','kecamatan','provinsi','rekening'];
    public function jabatan()
    {
        return $this->belongsTo(Jabatan::class, "id_jabatan", "id");
    }
    public function gaji()
    {
        return $this->hasMany(Gaji::class, "id_karyawan", "id");
    }
    public function detail()
    {
        return $this->hasMany(Detail::class, "id_karyawan", "id");
    }
}

Payroll/app/Http/Controllers/karyawan/karyawanController.php
<?php

namespace App\Http\Controllers\karyawan;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\karyawan\Karyawan;
use App\Models\jabatan\Jabatan;
use App\Models\User;
use Illuminate\Support\Facades\Hash;
use App\Http\Requests\karyawan\KaryawanStore;
use App\Http\Requests\karyawan\KaryawanUpdate;
use Illuminate\Support\Facades\Http;
class karyawanController extends Controller
{
    Const FETCHED_ATTRIBUTE = [
        'id_jabatan',
        'email',
        'nama',
        'alamat',
        'kabupaten',
        'kecamatan',
        'provinsi',
        'rekening'
    ];
    public function index()
    {
        $provinsi = Http::get('https://region-api.profileimage.studio/provinces');
        $data_provinsi = $provinsi->json('data');

        $kabupaten = Http::get('https://region-api.profileimage.studio/regencies');
        $data_kabupaten = $kabupaten->json('data');

        $kecamatan = Http::get('https://region-api.profileimage.studio/districts');
        $data_kecamatan = $kecamatan->json('data');
        $karyawan = Karyawan::with(['jabatan'])->orderBy('created_at', 'desc')
        ->get();

        return view('dashboard.content.karyawan.karyawan', compact('karyawan','data_provinsi','data_kecamatan','data_kabupaten'));
    }
    public function create()
    {
        
        $jabatan = Jabatan::get();
        $kecamatan = Http::get('http://region-api.profileimage.studio/districts');
        $data_kecamatan = $kecamatan->json('data');
        $kabupaten = Http::get('https://region-api.profileimage.studio/regencies');
        $data_kabupaten = $kabupaten->json('data');
        $provinsi = Http::get('https://region-api.profileimage.studio/provinces');
        $data_provinsi = $provinsi->json('data');
        $action = 'add';
        return view('dashboard.content.karyawan.karyawan-action', compact('action','data_provinsi','data_kecamatan','data_kabupaten','jabatan'));
    }

    public function store(KaryawanStore $request)
    {
        // dd('ss');
        $data = $request->only(self::FETCHED_ATTRIBUTE);
        $karyawan = karyawan::create($data);
        User::create([
            'id_role' => 2,
            'id_karyawan'=>$karyawan->id,
            'password'=>Hash::make($data['rekening']),
            'name' => $data['nama'],
            'email' => $data['email'],
            'isActive' => 1,

        ]);
        return redirect('/master/karyawan')->with(['success' => 'Data Berhasil Diupdate!']);
    }

    public function show($id)
    {
        //
    }
    public function edit($id)
    {
        $jabatan = Jabatan::get();
        $kecamatan = Http::get('http://region-api.profileimage.studio/districts');
        $data_kecamatan = $kecamatan->json('data');
        $kabupaten = Http::get('https://region-api.profileimage.studio/regencies');
        $data_kabupaten = $kabupaten->json('data');
        $provinsi = Http::get('https://region-api.profileimage.studio/provinces');
        $data_provinsi = $provinsi->json('data');
        $action = 'edit';
        $karyawan = karyawan::findOrFail($id);
        return view('dashboard.content.karyawan.karyawan-action', compact('action','data_provinsi','data_kecamatan','data_kabupaten','jabatan','karyawan'));
    }

    public function update(KaryawanUpdate $request, karyawan $karyawan)
    {
        $data = $request->only(self::FETCHED_ATTRIBUTE);
        $karyawan->update($data);
        User::where('id_karyawan',$karyawan->id)->update([
            'id_role' => 2,
            'id_karyawan'=>$karyawan->id,
            'password'=>Hash::make($data['rekening']),
            'name' => $data['nama'],
            'email' => $data['email'],
            'isActive' => 1,

        ]);
        return redirect('/master/karyawan')->with(['success' => 'Karyawan Berhasil Diubah!']);
    }

    public function destroy(karyawan $karyawan)
    {
        $user=User::where('id_karyawan',$karyawan->id)->delete();
        $karyawan->delete();
        return redirect('/master/karyawan')->with(['success' => 'Data Berhasil DiHapus!']);
    }
    public function kabupaten(Request $request)
    {
        $kabupaten = Http::get('https://region-api.profileimage.studio/regencies');
        $data_kabupaten = $kabupaten->json('data');
        $kab = [];
        foreach ($data_kabupaten as $item) {
            if ($item['province_id'] == $request->id) {
                array_push($kab, (object)[
                    'id' => $item['id'],
                    'name' => $item['name']
                ]);
            }
        }
        return response()->json($kab);
    }
    public function kecamatan(Request $request)
    {
        $kecamatan = Http::get('https://region-api.profileimage.studio/districts');
        $data_kecamatan = $kecamatan->json('data');
        $kec = [];
        foreach ($data_kecamatan as $item) {
            if ($item['regency_id'] == $request->id) {
                array_push($kec, (object)[
                    'id' => $item['id'],
                    'name' => $item['name']
                ]);
            }
        }
        return response()->json($kec);
    }
}

Payroll/resources/views/dashboard/content/karyawan/karyawan-action.blade.php
@extends('dashboard.dashboard')

@section('content')
<div class="container-fluid p-0">
  <div class="row d-flex justify-content-center">
    <div class="col-8">
        @if($action == 'add')
            <h1 class="h3 mb-3">Add New Karyawan</h1>
        @else
            <h1 class="h3 mb-3">Edit Karyawan</h1>
        @endif
      <div class="card">
        <div class="card-header">
          <h5 class="card-title mb-0">
            @if($action == 'add')
                <form id="karyawan-action" action="{{ route('karyawan.store') }}" method="POST" enctype="multipart/form-data">
            @else
                <form id="karyawan-action" action="{{ route('karyawan.update', $karyawan->id) }}" method="post" enctype="multipart/form-data">
                @method('put')
            @endif
                @csrf
                <div class="mb-3">
                    <label for="fullname" class="form-label">Nama Lengkap</label><span class="text-danger">*</span>
                    <input type="text" name="nama" class="form-control @error('nama') is-invalid @enderror" value="{{ old('nama') }}" id="nama" placeholder="Nama anda">
                    @error('nama')
                        <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>
                <div class="mb-3">
                  <label for="fullname" class="form-label">Email</label><span class="text-danger">*</span>
                  <input type="text" name="email" class="form-control @error('email') is-invalid @enderror" value="{{ old('email') }}" id="email" placeholder="email anda">
                  @error('email')
                      <div class="invalid-feedback">{{ $message }}</div>
                  @enderror
              </div>
                <!-- Jabatan -->
                <div class="mb-3">
                    <label for="job" class="form-label">Jabatan</label><span class="text-danger">*</span>
                    <select class="form-select @error('id_jabatan') is-invalid @enderror" name="id_jabatan" aria-label="Default select example" id="id_jabatan">
                    <option selected disabled value="">Jabatan Anda</option>
                    @foreach ($jabatan as $item)
                        <option value="{{$item['id']}}">{{$item['nama']}}</option>
                    @endforeach
                    @if ($action == 'edit')
                      @foreach ($jabatan as $item)
                          <option value="{{$item['id']}}" <?php if($karyawan->id_jabatan == $item['id']) { echo "selected";} ?>>{{$item['nama']}}</option>
                      @endforeach
                    @endif
                    @if(old('id_jabatan'))
                        @foreach($jabatan as $item)
                        <option value="{{$item['id']}}" {{ ($item['id'] == old('id_jabatan')) ? 'selected="selected"' : '' }}>{{$item['nama']}}</option>
                        @endforeach
                    @endif
                    </select>
                    @error('id_jabatan')
                        <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>

              
              <!-- Provinsi -->
              <div class="mb-3">
                    <label for="category" class="form-label">Provinsi</label><span class="text-danger">*</span>
                    <select class="form-select @error('provinsi') is-invalid @enderror" name="provinsi" id="provinsi" >                
                    <option selected disabled value="">Provinsi</option>
                    @foreach($data_provinsi as $provinsi)
                        <option value="{{$provinsi['id']}}" >{{$provinsi['name']}}</option>
                    @endforeach

                    @if ($action == 'edit')
                      @foreach($data_kabupaten as $kabupaten)
                        @foreach($data_provinsi as $provinsi)
                          @if($karyawan->kabupaten==$kabupaten['id'])
                              <option value="{{$provinsi['id']}}" <?php if($kabupaten['province_id'] == $provinsi['id']) { echo "selected";} ?>>{{$provinsi['name']}}</option>
                          @endif
                        @endforeach
                      @endforeach
                    @endif
                    
                    @if(old('provinsi'))
                      @foreach($data_kabupaten as $kabupaten)
                       <option value="{{$provinsi['id']}}" {{ ($kabupaten['province_id'] == old('provinsi')) ? 'selected="selected"' : '' }}>{{$provinsi['name']}}</option>
                             
                      @endforeach
                    @endif
                    </select>
                    @error('provinsi')
                        <div class="invalid-feedback">{{ $message }}</div>
                    @enderror
                </div>

              <!-- Kab/Kota -->
              <div class="mb-3">
                <label for="category" class="form-label">Kab/Kota</label><span class="text-danger">*</span>
                <select class="form-select @error('kabupaten') is-invalid @enderror"  name="kabupaten" id="kabupaten" >                
                  <option selected disabled value="">Kab/Kota</option>

                  @if ($action == 'edit')
                    @foreach($data_kabupaten as $kabupaten)
                      <option value="{{$kabupaten['id']}}" <?php if($karyawan->kabupaten == $kabupaten['id']) { echo "selected";} ?>>{{$kabupaten['name']}}</option>
                    @endforeach  
                  @endif
                  
                  @if(old('kabupaten'))
                    @foreach($data_kabupaten as $kabupaten)
                      <option value="{{$kabupaten['id']}}" {{ ($kabupaten['id'] == old('kabupaten')) ? 'selected="selected"' : '' }}>{{$kabupaten['name']}}</option>
                    @endforeach  
                  @endif
                </select>
                @error('kabupaten')
                    <div class="invalid-feedback">{{ $message }}</div>
                @enderror
              </div>

              <!-- Kecamatan -->
              <div class="mb-3">
                <label for="category" class="form-label">Kecamatan</label><span class="text-danger">*</span>
                <select class="form-select @error('kecamatan') is-invalid @enderror" name="kecamatan" id="kecamatan" >
                  <option selected disabled value="">Kecamatan</option>

                  @if ($action == 'edit')
                    @foreach($data_kecamatan as $kecamatan)
                      <option value="{{$kecamatan['id']}}" <?php if($karyawan->kecamatan == $kecamatan['id']) { echo "selected";} ?>>{{$kecamatan['name']}}</option>
                    @endforeach 
                  @endif
                  
                  @if(old('kecamatan'))
                    @foreach($data_kecamatan as $kecamatan)
                      <option value="{{$kecamatan['id']}}" {{ ($kecamatan['id'] == old('kecamatan')) ? 'selected="selected"' : '' }}>{{$kecamatan['name']}}</option>
                    @endforeach  
                  @endif            
                </select>
                @error('kecamatan')
                    <div class="invalid-feedback">{{ $message }}</div>
                @enderror
              </div>

              <!-- Alamat -->
              <div class="mb-3">
                <label for="fullname" class="form-label">Alamat</label><span class="text-danger">*</span>
                <input type="text" name="alamat" class="form-control @error('alamat') is-invalid @enderror" id="alamat" placeholder="Alamat anda" value="{{ old('alamat') }}">
                @error('alamat')
                    <div class="invalid-feedback">{{ $message }}</div>
                @enderror
              </div>
              <!-- nomer rekening -->
              <div class="mb-3">
                <label for="contact" class="form-label">Rekening</label><span class="text-danger">*</span>
                <input type="text" name="rekening" class="form-control @error('rekening') is-invalid @enderror" id="rekening" placeholder="Rekening" value="{{ old('rekening') }}">
                @error('rekening')
                    <div class="invalid-feedback">{{ $message }}</div>
                @enderror
              </div>

              <div class="d-flex justify-content-center">
                <a href="{{route('karyawan.index')}}" class="btn btn-light me-2">
                    <span class="btn-icon-label">
                      <i data-feather="arrow-left" class="me-2"></i>
                        <span> Kembali </span>
                    </span>
                </a>
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>
          </h5>
        </div>
        <div class="card-body">
        </div>
      </div>
    </div>
  </div>

</div>
@endsection

@section('page-script')
<script>

@if($action=='edit')
  const karyawan = {!! json_encode($karyawan->toArray()) !!}
    nama.value = karyawan.nama
    email.value = karyawan.email
    rekening.value = karyawan.rekening
    alamat.value = karyawan.alamat
@endif
  
    function onChangeSelect(url, id, name) {
        // send ajax request to get the cities of the selected province and append to the select tag
        $.ajax({
          url: url,
          type: 'GET',
          dataType: "json",
          data: {
            id: id
          },
          success: function (data) {
            
            $('#' + name).empty();
            if(name=="provinsi"){
              $('#' + name).append('<option selected disabled value="">Provinsi</option> ');
            }else if(name=="kabupaten"){
              $('#' + name).append('<option selected disabled value="">Kab/Kota</option> ');
            }else if(name=="kecamatan"){
              $('#' + name).append('<option selected disabled value="">Kecamatan</option> ');
            }
            data.forEach(el=>{
              $('#' + name).append('<option value="' + el.id + '">' + el.name    + '</option>');
            })
              // $.each(data, function (key, value) {
              //   console.log(key + value);
              //   // $('#sub_district' + name).append('<option value="' + key + '">' + value + '</option>');
              // });
          }
        });        
      }
      $(function () {
        $('#provinsi').on('change', function () {
          onChangeSelect('{{ route("kabupaten.kabupaten") }}', $(this).val(), 'kabupaten');
        });
        $('#kabupaten').on('change', function () {
          onChangeSelect('{{ route("kecamatan.kecamatan") }}', $(this).val(), 'kecamatan');
        });
      });

</script>
@endsection

Payroll/resources/views/dashboard/content/karyawan/karyawan.blade.php
@extends('dashboard.dashboard')

@section('content')
<div class="container-fluid p-0">

  <h1 class="h3 mb-3">Karyawan</h1>

  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header pt-4">
          <div class="d-flex justify-content-between align-items-center">
            <h5 class="card-title mb-0">Karyawan</h5>
            <a href="{{route('karyawan.create')}}" type="button" class="btn btn-primary">
              Add Karyawan</a>
          </div>

        </div>
        <div class="card-body">
          <table id="MyTable" class="table table-bordered" style="width:100%">
            <thead class="table-primary">
              <tr class="text-center">
                <th>
                  No.
                </th>
                <th>Nama</th>
                <th>Alamat</th>
                <th>Rekening</th>
                <th>Jabatan</th>
                @if (Auth::user()->id_role==1)
                  <th>Action</th>
                @endif
              </tr>
            </thead>
            <tbody>
              @forelse($karyawan as $item)
              <tr>
                <td class="text-center">{{$loop->iteration}}</td>
                <td>{{$item->nama}}</td>
                <td>
                    <span class="d-block mb-1">Provinsi : 
                        @foreach($data_kabupaten as $kabupaten)
                            @foreach($data_provinsi as $provinsi)
                                @if($item->kabupaten==$kabupaten['id'])
                                    @if ($kabupaten['province_id']==$provinsi['id'])
                                        <div class="col-9">{{$provinsi['name']}}</div>
                                    @endif
                                @endif
                            @endforeach
                        @endforeach</span>
                    <span class="d-block">Kab: 
                        @foreach ($data_kabupaten as $value)
                            @if ($item->kabupaten==$value['id'])
                            <div class="col-9">{{$value['name']}}</div>
                            @endif
                        @endforeach
                    </span>
                    <span class="d-block">Kec: 
                        @foreach ($data_kecamatan as $value)
                            @if ($item->kecamatan==$value['id'])
                                <div class="col-9">{{$value['name']}}</div>
                            @endif
                        @endforeach
                    </span>
                    <span class="d-block">Alamat: {{$item->alamat}}</span>
                    
                </td>
                <td>{{$item->rekening}}</td>
                <td>{{$item->jabatan->nama}}</td>
                @if (Auth::user()->id_role==1)
                  <td width="10" class="text-center">
                    <div class="d-flex justify-content-center">
                      <a class="btn btn-success" href="{{ route('karyawan.edit', $item->id) }}" role="button" data-bs-toggle="tooltip" data-bs-placement="top" title="Edit">
                          <i class="fas fa-edit"></i>
                      </a>
                      <button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#delete-modal" data-bs-id="{{$item->id}}" data-bs-act="{{ route('karyawan.destroy', $item->id) }}" data-bs-nama="{{$item->nama}}" data-bs-toggle="tooltip" data-bs-placement="top" title="Delate">
                          <i class="align-middle" data-feather="trash-2"></i>
                      </button>
                    </div>
                  </td>
                @endif
                
              </tr>
              @empty
              <tr>
                <td colspan="8">
                  <center>Data kosong</center>
                </td>
              </tr>
              @endforelse
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal modal-confirmation fade" id="delete-modal" tabindex='-1' role="dialog" aria-labelledby="deleteData" aria-hidden="true">
  <div class="modal-dialog modal-sm" role="document">
      <div class="modal-content">
          <form id="delete-form" action="/" method="post" enctype="multipart/form-data">
              @csrf
              <div class="modal-body">
                  <h4>Konfirmasi</h4>
                  <p class="mb-0">Yakin untuk menghapus <strong id="del-name"> </strong></p>
              </div>
              <div class="modal-footer">
                  @method('DELETE')
                  <button type="button" class="btn btn-link" data-bs-dismiss="modal">Batal</button>
                  <button type="submit" class="btn btn-danger">Hapus</button>
              </div>
          </form>
      </div>
  </div>
</div>

@endsection
<script>
  document.addEventListener("DOMContentLoaded", x => {

      const deleteModal = document.getElementById('delete-modal');
      const deleteForm = document.getElementById('delete-form');

      // Delete Modal Script
      deleteModal.addEventListener('show.bs.modal', evt => {
          let deleteBtn = event.relatedTarget;
          deleteForm.action = deleteBtn.getAttribute('data-bs-act');
          deleteModal.querySelector('#del-name').textContent = '"' + deleteBtn.getAttribute('data-bs-nama') + '" ?'
      })

  });
</script>